# Generated by Django 5.1.7 on 2025-03-22 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 14, 19, 51, 650091, tzinfo=datetime.timezone.utc)),
        ),
    ]
