# Generated by Django 5.1.7 on 2025-03-22 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_category_alter_contact_created_date_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 0, 47, 622738, tzinfo=datetime.timezone.utc)),
        ),
    ]
