# Generated by Django 5.1.7 on 2025-03-22 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_category_options_contact_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 16, 20, 33, 188549, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(default=True, null=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
