# Generated by Django 5.1.7 on 2025-03-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_created_date_alter_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 16, 48, 25, 733215, tzinfo=datetime.timezone.utc)),
        ),
    ]
